# ============================================================
#  SYSTEM PERFORMANCE & SECURITY AUDIT SCRIPT
#  Generated by Antigravity AI  |  Date: 2026-02-28
# ============================================================

param(
    [string]$ReportPath = "$env:USERPROFILE\Desktop\SystemAuditReport.html"
)

$ErrorActionPreference = "SilentlyContinue"

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host "  SYSTEM PERFORMANCE AND SECURITY AUDIT" -ForegroundColor Cyan
Write-Host "  Please wait while scanning your system..." -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""

function Write-Status($msg, $color = "Green") {
    Write-Host "  [*] $msg" -ForegroundColor $color
}

# ──────────────────────────────────────────────
# 1. SYSTEM INFO
# ──────────────────────────────────────────────
Write-Status "Collecting system information..." "Yellow"

$os        = Get-CimInstance Win32_OperatingSystem
$cs        = Get-CimInstance Win32_ComputerSystem
$cpu       = Get-CimInstance Win32_Processor | Select-Object -First 1
$bios      = Get-CimInstance Win32_BIOS
$disk      = Get-CimInstance Win32_LogicalDisk -Filter "DriveType=3"
$ram       = [math]::Round($cs.TotalPhysicalMemory / 1GB, 2)
$freeRam   = [math]::Round($os.FreePhysicalMemory / 1MB / 1024, 2)
$usedRam   = [math]::Round($ram - $freeRam, 2)
$ramPct    = [math]::Round(($usedRam / $ram) * 100, 1)
$uptime    = (Get-Date) - $os.LastBootUpTime
$uptimeStr = "{0}d {1}h {2}m" -f $uptime.Days, $uptime.Hours, $uptime.Minutes
$cpuLoad   = (Get-CimInstance Win32_Processor | Measure-Object -Property LoadPercentage -Average).Average

# ──────────────────────────────────────────────
# 2. DISK HEALTH AND SPACE
# ──────────────────────────────────────────────
Write-Status "Checking disk usage..." "Yellow"

$diskInfo = foreach ($d in $disk) {
    $total   = [math]::Round($d.Size / 1GB, 2)
    $free    = [math]::Round($d.FreeSpace / 1GB, 2)
    $used    = [math]::Round($total - $free, 2)
    $pct     = if ($total -gt 0) { [math]::Round(($used / $total) * 100, 1) } else { 0 }
    $status  = if ($pct -gt 90) { "CRITICAL" } elseif ($pct -gt 75) { "WARNING" } else { "OK" }
    [PSCustomObject]@{
        Drive  = $d.DeviceID
        Total  = "$total GB"
        Used   = "$used GB"
        Free   = "$free GB"
        UsePct = "$pct%"
        Status = $status
    }
}

# ──────────────────────────────────────────────
# 3. STARTUP PROGRAMS
# ──────────────────────────────────────────────
Write-Status "Auditing startup programs..." "Yellow"

$startupReg = @(
    "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run",
    "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run",
    "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Run"
)

$startupItems = foreach ($path in $startupReg) {
    if (Test-Path $path) {
        $reg = Get-ItemProperty -Path $path
        $reg.PSObject.Properties | Where-Object { $_.Name -notmatch "^PS" } | ForEach-Object {
            [PSCustomObject]@{ Name = $_.Name; Command = $_.Value; Source = $path }
        }
    }
}

# ──────────────────────────────────────────────
# 4. WINDOWS UPDATE STATUS
# ──────────────────────────────────────────────
Write-Status "Checking Windows Update status..." "Yellow"

$wuStatus = "Unknown"
$pendingUpdates = 0
try {
    $wuSession  = New-Object -ComObject Microsoft.Update.Session
    $wuSearcher = $wuSession.CreateUpdateSearcher()
    $wuResult   = $wuSearcher.Search("IsInstalled=0 and Type='Software'")
    $pendingUpdates = $wuResult.Updates.Count
    $wuStatus = if ($pendingUpdates -eq 0) { "Up to Date" } else { "$pendingUpdates updates pending" }
} catch {
    $wuStatus = "Could not query (may need elevation)"
}

# ──────────────────────────────────────────────
# 5. FIREWALL STATUS
# ──────────────────────────────────────────────
Write-Status "Checking Windows Firewall..." "Yellow"

$firewallProfiles = Get-NetFirewallProfile | Select-Object Name, Enabled
$fwDomain  = ($firewallProfiles | Where-Object Name -eq "Domain").Enabled
$fwPrivate = ($firewallProfiles | Where-Object Name -eq "Private").Enabled
$fwPublic  = ($firewallProfiles | Where-Object Name -eq "Public").Enabled

# ──────────────────────────────────────────────
# 6. OPEN PORTS
# ──────────────────────────────────────────────
Write-Status "Scanning open TCP ports..." "Yellow"

$openPorts = Get-NetTCPConnection -State Listen | Select-Object LocalPort, OwningProcess |
    Sort-Object LocalPort -Unique | ForEach-Object {
        $proc = Get-Process -Id $_.OwningProcess -ErrorAction SilentlyContinue
        $risk = switch ($_.LocalPort) {
            21   { "HIGH - FTP (unencrypted)" }
            23   { "CRITICAL - Telnet (unencrypted)" }
            80   { "INFO - HTTP Web Server" }
            135  { "MEDIUM - RPC" }
            139  { "MEDIUM - NetBIOS" }
            445  { "HIGH - SMB (potential EternalBlue)" }
            1433 { "MEDIUM - SQL Server" }
            3306 { "MEDIUM - MySQL" }
            3389 { "HIGH - RDP (brute-force risk)" }
            5985 { "MEDIUM - WinRM HTTP" }
            5986 { "MEDIUM - WinRM HTTPS" }
            8080 { "INFO - HTTP Alt" }
            default { "INFO - Other" }
        }
        [PSCustomObject]@{
            Port    = $_.LocalPort
            Process = if ($proc) { $proc.Name } else { "Unknown (PID: $($_.OwningProcess))" }
            Risk    = $risk
        }
    }

# ──────────────────────────────────────────────
# 7. USER ACCOUNTS AND PRIVILEGES
# ──────────────────────────────────────────────
Write-Status "Auditing user accounts..." "Yellow"

$localUsers = Get-LocalUser | Select-Object Name, Enabled, PasswordExpires, LastLogon, PasswordLastSet

$adminGroup = Get-LocalGroupMember -Group "Administrators" -ErrorAction SilentlyContinue |
    Select-Object Name, ObjectClass, PrincipalSource

$guestEnabled = (Get-LocalUser -Name "Guest" -ErrorAction SilentlyContinue).Enabled

# ──────────────────────────────────────────────
# 8. WINDOWS DEFENDER / ANTIVIRUS STATUS
# ──────────────────────────────────────────────
Write-Status "Checking antivirus/Defender status..." "Yellow"

$defenderStatus = $null
try {
    $defenderStatus = Get-MpComputerStatus
} catch {}

$avProducts = Get-CimInstance -Namespace root/SecurityCenter2 -ClassName AntiVirusProduct -ErrorAction SilentlyContinue |
    Select-Object displayName, productState

# ──────────────────────────────────────────────
# 9. SHARED FOLDERS
# ──────────────────────────────────────────────
Write-Status "Checking network shares..." "Yellow"

$shares = Get-SmbShare | Where-Object { $_.Name -notmatch "^\w+\$$" -and $_.Name -ne "IPC$" } |
    Select-Object Name, Path, Description

# ──────────────────────────────────────────────
# 10. SUSPICIOUS SCHEDULED TASKS
# ──────────────────────────────────────────────
Write-Status "Auditing scheduled tasks..." "Yellow"

$schedTasks = Get-ScheduledTask | Where-Object {
    $_.State -eq "Ready" -and $_.TaskPath -notmatch "^\\Microsoft\\"
} | Select-Object TaskName, TaskPath, State | Sort-Object TaskPath

# ──────────────────────────────────────────────
# 11. RUNNING PROCESSES (Top CPU and Memory)
# ──────────────────────────────────────────────
Write-Status "Analyzing running processes..." "Yellow"

$topCpu = Get-Process | Sort-Object CPU -Descending | Select-Object -First 10 |
    Select-Object Name, Id, @{N='CPU(s)';E={[math]::Round($_.CPU,1)}}, @{N='RAM(MB)';E={[math]::Round($_.WorkingSet/1MB,1)}}

$topRam = Get-Process | Sort-Object WorkingSet -Descending | Select-Object -First 10 |
    Select-Object Name, Id, @{N='CPU(s)';E={[math]::Round($_.CPU,1)}}, @{N='RAM(MB)';E={[math]::Round($_.WorkingSet/1MB,1)}}

# ──────────────────────────────────────────────
# 12. TEMP FILES SIZE
# ──────────────────────────────────────────────
Write-Status "Calculating temp file sizes..." "Yellow"

function Get-FolderSize($path) {
    if (Test-Path $path) {
        $size = (Get-ChildItem $path -Recurse -Force -ErrorAction SilentlyContinue |
            Measure-Object -Property Length -Sum).Sum
        [math]::Round($size / 1MB, 1)
    } else { 0 }
}

$tempSize   = Get-FolderSize $env:TEMP
$winTmp     = Get-FolderSize "C:\Windows\Temp"
$prefetch   = Get-FolderSize "C:\Windows\Prefetch"
$totalJunk  = [math]::Round($tempSize + $winTmp + $prefetch, 1)

# ──────────────────────────────────────────────
# 13. SYSTEM EVENT ERRORS (last 24h)
# ──────────────────────────────────────────────
Write-Status "Checking system event errors..." "Yellow"

$since = (Get-Date).AddHours(-24)
$sysErrors = Get-WinEvent -FilterHashtable @{LogName='System'; Level=2; StartTime=$since} -MaxEvents 20 -ErrorAction SilentlyContinue |
    Select-Object TimeCreated, Id, Message | ForEach-Object {
        [PSCustomObject]@{
            Time    = $_.TimeCreated.ToString("yyyy-MM-dd HH:mm")
            EventId = $_.Id
            Message = ($_.Message -split "`n")[0] -replace "<[^>]+>", ""
        }
    }

$appErrors = Get-WinEvent -FilterHashtable @{LogName='Application'; Level=2; StartTime=$since} -MaxEvents 20 -ErrorAction SilentlyContinue |
    Select-Object TimeCreated, Id, Message | ForEach-Object {
        [PSCustomObject]@{
            Time    = $_.TimeCreated.ToString("yyyy-MM-dd HH:mm")
            EventId = $_.Id
            Message = ($_.Message -split "`n")[0] -replace "<[^>]+>", ""
        }
    }

# ──────────────────────────────────────────────
# 14. POWER PLAN
# ──────────────────────────────────────────────
Write-Status "Checking power plan..." "Yellow"

$powerPlan = powercfg /getactivescheme 2>$null
$planName  = if ($powerPlan -match "([A-Za-z ]+)\s*$") { $Matches[1].Trim() } else { "Unknown" }

# ──────────────────────────────────────────────
# 15. UAC STATUS
# ──────────────────────────────────────────────
$uacKey     = Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" -ErrorAction SilentlyContinue
$uacEnabled = if ($uacKey.EnableLUA -eq 1) { "Enabled" } else { "DISABLED - Security Risk" }

# ──────────────────────────────────────────────
# SCORE CALCULATION
# ──────────────────────────────────────────────
$issues    = [System.Collections.Generic.List[string]]::new()
$score     = 100

if (-not $fwPublic)  { $score -= 15; $issues.Add("Public Firewall is DISABLED") }
if (-not $fwPrivate) { $score -= 10; $issues.Add("Private Firewall is DISABLED") }
if (-not $fwDomain)  { $score -= 5;  $issues.Add("Domain Firewall is DISABLED") }
if ($guestEnabled)   { $score -= 10; $issues.Add("Guest account is ENABLED") }
if ($uacKey.EnableLUA -ne 1) { $score -= 15; $issues.Add("UAC is DISABLED - critical risk") }
if ($pendingUpdates -gt 0)   { $score -= [math]::Min($pendingUpdates * 2, 20); $issues.Add("$pendingUpdates Windows Updates are PENDING") }

$highRiskPorts = $openPorts | Where-Object { $_.Risk -match "HIGH|CRITICAL" }
foreach ($p in $highRiskPorts) { $score -= 5; $issues.Add("High-risk port open: $($p.Port) - $($p.Risk)") }

foreach ($d in $diskInfo) {
    if ($d.Status -eq "CRITICAL") { $score -= 10; $issues.Add("Disk $($d.Drive) is CRITICALLY FULL ($($d.UsePct))") }
    elseif ($d.Status -eq "WARNING") { $score -= 5; $issues.Add("Disk $($d.Drive) is getting full ($($d.UsePct))") }
}

if ($ramPct -gt 85) { $score -= 10; $issues.Add("RAM usage is very high: $ramPct%") }

if ($defenderStatus -and -not $defenderStatus.RealTimeProtectionEnabled) {
    $score -= 15; $issues.Add("Windows Defender Real-Time Protection is OFF")
}
if ($defenderStatus -and $defenderStatus.AntivirusSignatureAge -gt 7) {
    $score -= 8; $issues.Add("Defender virus definitions are $($defenderStatus.AntivirusSignatureAge) days old")
}

$score      = [math]::Max($score, 0)
$grade      = if ($score -ge 85) { "A - Excellent" } elseif ($score -ge 70) { "B - Good" } elseif ($score -ge 55) { "C - Fair" } elseif ($score -ge 40) { "D - Poor" } else { "F - Critical" }
$scoreColor = if ($score -ge 85) { "#22c55e" } elseif ($score -ge 70) { "#84cc16" } elseif ($score -ge 55) { "#eab308" } elseif ($score -ge 40) { "#f97316" } else { "#ef4444" }

# ──────────────────────────────────────────────
# HTML REPORT GENERATION
# ──────────────────────────────────────────────
Write-Status "Generating HTML report..." "Cyan"

Add-Type -AssemblyName System.Web

function ConvertTo-HtmlTable($objects, $highlight = $null) {
    if (-not $objects -or @($objects).Count -eq 0) { return "<p class='none'>No items found.</p>" }
    $cols = ($objects | Select-Object -First 1).PSObject.Properties.Name
    $html = "<table><thead><tr>"
    foreach ($c in $cols) { $html += "<th>$c</th>" }
    $html += "</tr></thead><tbody>"
    foreach ($row in $objects) {
        $rowClass = ""
        if ($highlight) {
            $val = $row.$highlight
            if ($val -match "CRITICAL|DISABLED|HIGH") { $rowClass = " class='row-critical'" }
            elseif ($val -match "WARNING|MEDIUM") { $rowClass = " class='row-warning'" }
            elseif ($val -match "OK|Enabled|Up to Date") { $rowClass = " class='row-ok'" }
        }
        $html += "<tr$rowClass>"
        foreach ($c in $cols) {
            $cellVal = if ($null -ne $row.$c) { [System.Web.HttpUtility]::HtmlEncode($row.$c.ToString()) } else { "" }
            $html += "<td>$cellVal</td>"
        }
        $html += "</tr>"
    }
    $html += "</tbody></table>"
    return $html
}

$reportDate    = Get-Date -Format "dddd, MMMM dd yyyy  HH:mm:ss"
$issueListHtml = if ($issues.Count -eq 0) {
    "<li class='ok-item'>No major issues detected - your system looks clean!</li>"
} else {
    ($issues | ForEach-Object { "<li class='issue-item'>$_</li>" }) -join ""
}

$defenderHtml = if ($defenderStatus) {
    $rtClass = if ($defenderStatus.RealTimeProtectionEnabled) { "val-ok" } else { "val-bad" }
    $rtVal   = if ($defenderStatus.RealTimeProtectionEnabled) { "Enabled" } else { "DISABLED" }
    $sigAge  = $defenderStatus.AntivirusSignatureAge
    $sigClass = if ($sigAge -le 3) { "val-ok" } else { "val-bad" }
    "<table><thead><tr><th>Property</th><th>Value</th></tr></thead><tbody>" +
    "<tr><td>Real-Time Protection</td><td class='$rtClass'>$rtVal</td></tr>" +
    "<tr><td>AM Engine Version</td><td>$($defenderStatus.AMEngineVersion)</td></tr>" +
    "<tr><td>Signature Version</td><td>$($defenderStatus.AntivirusSignatureVersion)</td></tr>" +
    "<tr><td>Signature Age (days)</td><td class='$sigClass'>$sigAge</td></tr>" +
    "<tr><td>Quick Scan Age (days)</td><td>$($defenderStatus.QuickScanAge)</td></tr>" +
    "<tr><td>Full Scan Age (days)</td><td>$($defenderStatus.FullScanAge)</td></tr>" +
    "</tbody></table>"
} else {
    "<p class='warn'>Windows Defender status could not be retrieved.</p>"
}

$fwHtml = "<table><thead><tr><th>Profile</th><th>Status</th></tr></thead><tbody>" +
    "<tr><td>Domain</td><td class='$(if($fwDomain){'val-ok'}else{'val-bad'})'>$(if($fwDomain){'Enabled'}else{'DISABLED'})</td></tr>" +
    "<tr><td>Private</td><td class='$(if($fwPrivate){'val-ok'}else{'val-bad'})'>$(if($fwPrivate){'Enabled'}else{'DISABLED'})</td></tr>" +
    "<tr><td>Public</td><td class='$(if($fwPublic){'val-ok'}else{'val-bad'})'>$(if($fwPublic){'Enabled'}else{'DISABLED'})</td></tr>" +
    "</tbody></table>"

$ramBarColor = if ($ramPct -gt 85) { "#ef4444" } elseif ($ramPct -gt 65) { "#f97316" } else { "#22c55e" }
$cpuBarColor = if ($cpuLoad -gt 85) { "#ef4444" } elseif ($cpuLoad -gt 65) { "#f97316" } else { "#22c55e" }

$diskBarsHtml = ""
foreach ($d in $diskInfo) {
    $pct      = [double]($d.UsePct -replace "%", "")
    $barColor = if ($pct -gt 90) { "#ef4444" } elseif ($pct -gt 75) { "#f97316" } else { "#22c55e" }
    $statusBadge = if ($d.Status -eq "OK") { "ok" } elseif ($d.Status -eq "WARNING") { "warn" } else { "bad" }
    $diskBarsHtml += "<div class='metric-card'>"
    $diskBarsHtml += "<div class='metric-label'>Disk $($d.Drive) - $($d.Used) / $($d.Total) used</div>"
    $diskBarsHtml += "<div class='bar-bg'><div class='bar-fill' style='width:$pct%;background:$barColor'></div></div>"
    $diskBarsHtml += "<div class='bar-label'>$($d.UsePct) used - $($d.Free) free <span class='badge badge-$statusBadge'>$($d.Status)</span></div>"
    $diskBarsHtml += "</div>"
}

$html = @"
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>System Audit Report - $($cs.Name)</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=JetBrains+Mono:wght@400;500&display=swap');
  *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
  :root{
    --bg:#0a0e1a;--bg2:#111827;--bg3:#1a2235;--card:#141c2e;
    --border:#1e2d4a;--accent:#3b82f6;--accent2:#8b5cf6;
    --text:#e2e8f0;--muted:#64748b;--ok:#22c55e;--warn:#eab308;--bad:#ef4444;
  }
  body{background:var(--bg);color:var(--text);font-family:'Inter',sans-serif;line-height:1.6}
  header{
    background:linear-gradient(135deg,#0f172a 0%,#1e1b4b 50%,#0f172a 100%);
    border-bottom:1px solid var(--border);padding:3rem 2rem 2rem;text-align:center;
    position:relative;overflow:hidden;
  }
  header::before{content:'';position:absolute;inset:0;background:radial-gradient(ellipse at 50% 0%,rgba(59,130,246,.15) 0%,transparent 70%)}
  header h1{font-size:2.2rem;font-weight:800;letter-spacing:-.5px;
    background:linear-gradient(90deg,#60a5fa,#a78bfa);-webkit-background-clip:text;-webkit-text-fill-color:transparent}
  header .subtitle{color:var(--muted);margin-top:.5rem;font-size:.95rem}
  header .date{color:#475569;font-size:.85rem;margin-top:.3rem}
  .score-ring{
    width:140px;height:140px;border-radius:50%;border:8px solid $scoreColor;
    display:flex;flex-direction:column;align-items:center;justify-content:center;
    margin:2rem auto 1rem;box-shadow:0 0 40px ${scoreColor}55;background:var(--card);
  }
  .score-ring .score-num{font-size:3rem;font-weight:800;color:$scoreColor;line-height:1}
  .score-ring .score-label{font-size:.75rem;color:var(--muted)}
  .grade{font-size:1.1rem;font-weight:600;color:$scoreColor;margin-bottom:1rem}
  .container{max-width:1200px;margin:0 auto;padding:2rem}
  .grid-2{display:grid;grid-template-columns:1fr 1fr;gap:1.5rem}
  .grid-3{display:grid;grid-template-columns:repeat(3,1fr);gap:1.2rem}
  @media(max-width:768px){.grid-2,.grid-3{grid-template-columns:1fr}}
  section{margin-bottom:2.5rem}
  .section-title{
    font-size:1.1rem;font-weight:700;color:var(--accent);
    border-left:4px solid var(--accent);padding-left:.75rem;
    margin-bottom:1.2rem;display:flex;align-items:center;gap:.5rem;
  }
  .card{background:var(--card);border:1px solid var(--border);border-radius:12px;padding:1.5rem;transition:border-color .2s}
  .card:hover{border-color:var(--accent)}
  .stat-card{text-align:center;padding:1.2rem}
  .stat-card .stat-val{font-size:1.6rem;font-weight:800;color:var(--accent)}
  .stat-card .stat-lbl{font-size:.8rem;color:var(--muted);margin-top:.2rem}
  table{width:100%;border-collapse:collapse;font-size:.875rem}
  thead tr{background:rgba(59,130,246,.1);border-bottom:1px solid var(--border)}
  th{padding:.7rem 1rem;text-align:left;font-weight:600;color:#93c5fd;font-size:.8rem;text-transform:uppercase;letter-spacing:.05em}
  td{padding:.65rem 1rem;border-bottom:1px solid rgba(255,255,255,.04);font-family:'JetBrains Mono',monospace;font-size:.82rem;word-break:break-all}
  tr:last-child td{border-bottom:none}
  tr:hover td{background:rgba(59,130,246,.05)}
  .row-critical td{background:rgba(239,68,68,.08)}
  .row-warning td{background:rgba(234,179,8,.07)}
  .row-ok td{background:rgba(34,197,94,.06)}
  .val-ok{color:var(--ok)!important;font-weight:600}
  .val-bad{color:var(--bad)!important;font-weight:700}
  .val-warn{color:var(--warn)!important;font-weight:600}
  .badge{display:inline-block;padding:.15rem .55rem;border-radius:999px;font-size:.72rem;font-weight:700;font-family:'Inter',sans-serif}
  .badge-ok{background:rgba(34,197,94,.2);color:var(--ok)}
  .badge-warn{background:rgba(234,179,8,.2);color:var(--warn)}
  .badge-bad{background:rgba(239,68,68,.2);color:var(--bad)}
  .bar-bg{background:rgba(255,255,255,.07);border-radius:999px;height:8px;margin:.5rem 0;overflow:hidden}
  .bar-fill{height:100%;border-radius:999px;transition:width .5s}
  .bar-label{font-size:.8rem;color:var(--muted)}
  .metric-label{font-size:.875rem;font-weight:500;margin-bottom:.25rem;color:var(--text)}
  .metric-card{margin-bottom:1.2rem}
  .issues-list{list-style:none}
  .issue-item{padding:.6rem 1rem;margin-bottom:.5rem;border-radius:8px;background:rgba(239,68,68,.08);border-left:3px solid var(--bad);font-size:.875rem}
  .ok-item{padding:.6rem 1rem;border-radius:8px;background:rgba(34,197,94,.08);border-left:3px solid var(--ok);font-size:.875rem}
  .none{color:var(--muted);font-style:italic;font-size:.875rem}
  .warn{color:var(--warn);font-size:.875rem}
  .tips{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:1rem}
  .tip-card{background:var(--card);border:1px solid var(--border);border-radius:10px;padding:1.2rem}
  .tip-card h4{color:var(--accent2);font-size:.875rem;font-weight:700;margin-bottom:.4rem}
  .tip-card p{font-size:.8rem;color:var(--muted);line-height:1.5}
  footer{text-align:center;padding:2rem;border-top:1px solid var(--border);color:var(--muted);font-size:.8rem}
</style>
</head>
<body>

<header>
  <h1>System Audit Report</h1>
  <div class="subtitle">Host: <strong>$($cs.Name)</strong> &nbsp;|&nbsp; User: <strong>$($env:USERNAME)</strong> &nbsp;|&nbsp; OS: <strong>$($os.Caption)</strong></div>
  <div class="date">Generated: $reportDate</div>
  <div class="score-ring">
    <div class="score-num">$score</div>
    <div class="score-label">/ 100</div>
  </div>
  <div class="grade">Security Grade: $grade</div>
</header>

<div class="container">

<section>
  <div class="grid-3">
    <div class="card stat-card">
      <div class="stat-val">$($cpu.NumberOfCores) Cores</div>
      <div class="stat-lbl">CPU Load: $cpuLoad%</div>
    </div>
    <div class="card stat-card">
      <div class="stat-val">$ram GB RAM</div>
      <div class="stat-lbl">$usedRam GB used ($ramPct%)</div>
    </div>
    <div class="card stat-card">
      <div class="stat-val">$uptimeStr</div>
      <div class="stat-lbl">System Uptime</div>
    </div>
  </div>
</section>

<section>
  <div class="section-title">Security Issues Found ($($issues.Count))</div>
  <div class="card">
    <ul class="issues-list">$issueListHtml</ul>
  </div>
</section>

<section>
  <div class="section-title">Performance Metrics</div>
  <div class="grid-2">
    <div class="card">
      <div class="metric-card">
        <div class="metric-label">CPU Load</div>
        <div class="bar-bg"><div class="bar-fill" style="width:$($cpuLoad)%;background:$cpuBarColor"></div></div>
        <div class="bar-label">$cpuLoad% avg - $($cpu.NumberOfCores) cores / $($cpu.NumberOfLogicalProcessors) threads</div>
      </div>
      <div class="metric-card">
        <div class="metric-label">RAM Usage ($usedRam GB / $ram GB)</div>
        <div class="bar-bg"><div class="bar-fill" style="width:$ramPct%;background:$ramBarColor"></div></div>
        <div class="bar-label">$ramPct% used - $freeRam GB free</div>
      </div>
    </div>
    <div class="card">$diskBarsHtml</div>
  </div>
</section>

<section>
  <div class="section-title">Top CPU Processes</div>
  <div class="card">$(ConvertTo-HtmlTable $topCpu)</div>
</section>

<section>
  <div class="section-title">Top RAM Processes</div>
  <div class="card">$(ConvertTo-HtmlTable $topRam)</div>
</section>

<section>
  <div class="section-title">Windows Firewall</div>
  <div class="card">$fwHtml</div>
</section>

<section>
  <div class="section-title">Windows Defender / Antivirus</div>
  <div class="card">$defenderHtml</div>
</section>

<section>
  <div class="section-title">Open Network Ports</div>
  <div class="card">$(ConvertTo-HtmlTable ($openPorts | Sort-Object Risk -Descending) "Risk")</div>
</section>

<section>
  <div class="section-title">User Accounts</div>
  <div class="grid-2">
    <div>
      <div class="section-title" style="font-size:.9rem;margin-top:0">All Local Users</div>
      <div class="card">$(ConvertTo-HtmlTable $localUsers)</div>
    </div>
    <div>
      <div class="section-title" style="font-size:.9rem;margin-top:0">Administrators Group</div>
      <div class="card">$(ConvertTo-HtmlTable $adminGroup)</div>
    </div>
  </div>
</section>

<section>
  <div class="section-title">Security Settings</div>
  <div class="card">
    <table><thead><tr><th>Setting</th><th>Status</th></tr></thead><tbody>
    <tr><td>User Account Control (UAC)</td><td>$uacEnabled</td></tr>
    <tr><td>Guest Account</td><td class="$(if($guestEnabled){'val-bad'}else{'val-ok'})">$(if($guestEnabled){'ENABLED - Risk'}else{'Disabled - Good'})</td></tr>
    <tr><td>Windows Update</td><td class="$(if($pendingUpdates -eq 0){'val-ok'}else{'val-warn'})">$wuStatus</td></tr>
    <tr><td>Active Power Plan</td><td>$planName</td></tr>
    </tbody></table>
  </div>
</section>

<section>
  <div class="section-title">Startup Programs ($(@($startupItems).Count))</div>
  <div class="card">$(ConvertTo-HtmlTable $startupItems)</div>
</section>

<section>
  <div class="section-title">Network Shares</div>
  <div class="card">$(if ($shares) { ConvertTo-HtmlTable $shares } else { "<p class='none'>No non-administrative shares found.</p>" })</div>
</section>

<section>
  <div class="section-title">Non-Microsoft Scheduled Tasks ($(@($schedTasks).Count))</div>
  <div class="card">$(ConvertTo-HtmlTable $schedTasks)</div>
</section>

<section>
  <div class="section-title">Junk and Temp Files</div>
  <div class="card">
    <table><thead><tr><th>Location</th><th>Size</th></tr></thead><tbody>
    <tr><td>User Temp (%TEMP%)</td><td>$tempSize MB</td></tr>
    <tr><td>C:\Windows\Temp</td><td>$winTmp MB</td></tr>
    <tr><td>C:\Windows\Prefetch</td><td>$prefetch MB</td></tr>
    <tr><td><strong>Total Junk</strong></td><td><strong>$totalJunk MB</strong></td></tr>
    </tbody></table>
  </div>
</section>

<section>
  <div class="section-title">System Errors (Last 24 Hours)</div>
  <div class="card">$(if ($sysErrors) { ConvertTo-HtmlTable $sysErrors } else { "<p class='none'>No critical system errors in the last 24 hours.</p>" })</div>
</section>

<section>
  <div class="section-title">Application Errors (Last 24 Hours)</div>
  <div class="card">$(if ($appErrors) { ConvertTo-HtmlTable $appErrors } else { "<p class='none'>No critical application errors in the last 24 hours.</p>" })</div>
</section>

<section>
  <div class="section-title">System Information</div>
  <div class="card">
    <table><thead><tr><th>Property</th><th>Value</th></tr></thead><tbody>
    <tr><td>Hostname</td><td>$($cs.Name)</td></tr>
    <tr><td>OS</td><td>$($os.Caption) $($os.OSArchitecture)</td></tr>
    <tr><td>OS Version</td><td>$($os.Version)</td></tr>
    <tr><td>Build Number</td><td>$($os.BuildNumber)</td></tr>
    <tr><td>CPU</td><td>$($cpu.Name)</td></tr>
    <tr><td>Cores / Threads</td><td>$($cpu.NumberOfCores) / $($cpu.NumberOfLogicalProcessors)</td></tr>
    <tr><td>Total RAM</td><td>$ram GB</td></tr>
    <tr><td>Manufacturer / Model</td><td>$($cs.Manufacturer) $($cs.Model)</td></tr>
    <tr><td>BIOS Version</td><td>$($bios.SMBIOSBIOSVersion)</td></tr>
    <tr><td>BIOS Release Date</td><td>$($bios.ReleaseDate)</td></tr>
    <tr><td>Last Boot Time</td><td>$($os.LastBootUpTime)</td></tr>
    <tr><td>Uptime</td><td>$uptimeStr</td></tr>
    </tbody></table>
  </div>
</section>

<section>
  <div class="section-title">Optimization Recommendations</div>
  <div class="tips">
    <div class="tip-card"><h4>Clean Temp Files</h4><p>Run Disk Cleanup (cleanmgr) or delete %TEMP% contents. Could save $totalJunk MB immediately.</p></div>
    <div class="tip-card"><h4>Manage Startup Programs</h4><p>Disable unnecessary startup programs via Task Manager &gt; Startup tab to speed up boot time.</p></div>
    <div class="tip-card"><h4>Set High Performance Plan</h4><p>Run: powercfg /setactive 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c for maximum CPU performance.</p></div>
    <div class="tip-card"><h4>Update Windows Regularly</h4><p>Keeping Windows updated patches security vulnerabilities and improves system stability.</p></div>
    <div class="tip-card"><h4>Keep Defender Active</h4><p>Always keep Windows Defender real-time protection enabled and signatures up to date.</p></div>
    <div class="tip-card"><h4>Review Open Ports</h4><p>Disable or block high-risk ports (RDP 3389, SMB 445, Telnet 23) if not actively needed.</p></div>
    <div class="tip-card"><h4>Manage RAM Usage</h4><p>Close unused apps and browser tabs. Consider virtual memory increase if RAM stays above 85%.</p></div>
    <div class="tip-card"><h4>Defragment HDD</h4><p>If on HDD (not SSD), run: defrag C: /U /V for better disk read/write performance.</p></div>
    <div class="tip-card"><h4>Review Admin Accounts</h4><p>Ensure only trusted users are in the Administrators group. Use standard accounts daily.</p></div>
  </div>
</section>

</div>
<footer>
  <p>System Audit Report &middot; Generated by Antigravity AI &middot; $reportDate</p>
  <p style="margin-top:.3rem;font-size:.75rem;">This report is for informational purposes. Consult a security professional for critical environments.</p>
</footer>
</body>
</html>
"@

$html | Out-File -FilePath $ReportPath -Encoding UTF8

Write-Host ""
Write-Host "============================================" -ForegroundColor Green
Write-Host "  AUDIT COMPLETE!" -ForegroundColor Green
Write-Host "============================================" -ForegroundColor Green
Write-Host ""
Write-Host "  Security Score : $score / 100  ($grade)" -ForegroundColor $(if($score -ge 70){"Green"}elseif($score -ge 50){"Yellow"}else{"Red"})
Write-Host "  Issues Found   : $($issues.Count)" -ForegroundColor $(if($issues.Count -eq 0){"Green"}else{"Yellow"})
Write-Host "  Report Path    : $ReportPath" -ForegroundColor Cyan
Write-Host ""
if ($issues.Count -gt 0) {
    Write-Host "  Top Issues Detected:" -ForegroundColor Yellow
    $issues | Select-Object -First 8 | ForEach-Object { Write-Host "    [!] $_" -ForegroundColor Red }
}
Write-Host ""
Write-Host "  Opening HTML report in your browser..." -ForegroundColor Cyan
Start-Process $ReportPath
